### ISSUE TITLE
Movie Table component width

### ISSUE THREAD

**Issue by jacobbailey8** [jacobbailey8/movie-app#15]
Something with the Movie table component is set to push the drawer to the right. Must be something with the css I'm not sure yet what.

**Comment by jacobbailey8** [comment]
This is not yet on main branch

**Comment by DevinLust** [comment]
what is the drawer?

**Comment by jacobbailey8** [comment]
im redesigning the sidebar on mobile right now to open and close a drawer for the different links

**Comment by jacobbailey8** [comment]
it will be on sidebar-redesign branch
